In [3]:
import numpy as np

In [31]:
a = np.array([1,'1'])

In [32]:
a

array(['1', '1'], dtype='<U11')

array는 데이터타입이 같아야하므로 통일되었음

In [7]:
a = np.array([1,2,3,4])

In [8]:
a

array([1, 2, 3, 4])

In [9]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [10]:
a.sum()

10

In [34]:
a = np.array(range(10000000))

In [35]:
a

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [15]:
%timeit a.sum()

5.11 ms ± 298 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [17]:
%timeit sum(range(10000000))

589 ms ± 39.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


명백하게 numpy가 빠르다.

In [19]:
a = np.array(range(10000000))

In [21]:
b = np.ones((10,3))

In [22]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
b = np.zeros((2,3,4))

In [52]:
b

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [37]:
b = np.eye(4)

In [40]:
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
c = np.empty(5)

In [39]:
c

array([1.34898725e-311, 1.77948730e+248, 1.28372635e+248, 1.91158106e+214,
       0.00000000e+000])

In [42]:
d = np.arange(1,11)

In [43]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
d[1]

2

인덱싱이 가능하다. numpy로 생성한 배열은 시퀀스.

In [74]:
e = np.array([[1,2,3],[4,5,6]])

In [75]:
e[1][2]

6

In [76]:
e.shape

(2, 3)

shape은 이 배열이 몇행 몇열짜리인지 알려준다.

In [77]:
e.ndim

2

몇 차원 데이터인지 알려준다. 왜 2차원?
(2,4) -> 점의 좌표. 1차원
(2,5,7) -> 면에서의 좌표. 2차원

In [78]:
e.dtype

dtype('int32')

구성되어 있는 데이터타입이 어떤 데이터타입인지 보여준다.
int면 int지 왜 int32?
numpy는 C로 구현했기 때문에 데이터타입이 세분화 되어있다.
그래서 속도가 빠른 것.

In [79]:
e.strides #등간격

(12, 4)