In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.pi

3.141592653589793

In [5]:
np.pi +=1

In [6]:
np.pi

4.141592653589793

In [7]:
np.newaxis is None

True

In [8]:
None

In [15]:
a[np.newaxis]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [18]:
a[np.newaxis].shape

(1, 2, 3)

In [19]:
a.shape

(2, 3)

In [25]:
a[:,np.newaxis].shape

(2, 1, 3)

In [28]:
a[:,:,np.newaxis]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [29]:
a.swapaxes(0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
a = np.array([[[1],[2],[3]],[[4],[5],[6]]])

In [34]:
a.shape

(2, 3, 1)

In [33]:
a.swapaxes(0,2)

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [38]:
a = np.arange(6).reshape(2,-1)

In [42]:
b = np.arange(6,12).reshape(-1,3)

In [43]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [46]:
np.stack((a,b),axis=2)

array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])

In [45]:
np.dstack((a,b))

array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])

In [47]:
x = np.vstack((a,b))

In [48]:
np.vsplit(x,(2,3))

[array([[0, 1, 2],
        [3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]

In [49]:
np.vsplit(x,(2,2))

[array([[0, 1, 2],
        [3, 4, 5]]), array([], shape=(0, 3), dtype=int32), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [50]:
np.vsplit(x,(2,1))

[array([[0, 1, 2],
        [3, 4, 5]]), array([], shape=(0, 3), dtype=int32), array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])]

In [52]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [51]:
np.meshgrid(np.linspace(0,1,3),np.linspace(0,1,3)) #linspace는 linespace. 

[array([[0. , 0.5, 1. ],
        [0. , 0.5, 1. ],
        [0. , 0.5, 1. ]]), array([[0. , 0. , 0. ],
        [0.5, 0.5, 0.5],
        [1. , 1. , 1. ]])]

In [53]:
a = np.ix_([0,1],[1,2])

In [65]:
dt = np.dtype([('moon',np.int16),('sun','i4')])

In [66]:
a = np.array([1,2,3],dtype=dt)

In [67]:
a['moon']

array([1, 2, 3], dtype=int16)

In [68]:
a['sun']

array([1, 2, 3])