In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6,7,8])

In [18]:
a = a.reshape((2,4))

In [65]:
a = a.reshape((4,2))

In [66]:
a

array([[1, 2],
       [3, 0],
       [5, 6],
       [7, 8]])

In [67]:
b = a.copy()

In [69]:
b[0][0] = 100

In [70]:
c

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [73]:
b[0,0]

100

In [64]:
c = [[1,2,3,4],[5,6,7,8]]

In [14]:
c[2,1] #파이썬 자체적으로는 이런 문법을 지원하지 않는다.

TypeError: list indices must be integers or slices, not tuple

In [26]:
a = np.array([1,2,3,4,5,6,7,8])

In [27]:
b=a

In [28]:
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
b[3] = 0

In [30]:
a

array([1, 2, 3, 0, 5, 6, 7, 8])

In [31]:
b

array([1, 2, 3, 0, 5, 6, 7, 8])

In [53]:
d = [[1,2,3],[4,5,6]]

In [56]:
import copy
e = copy.deepcopy(d)

In [57]:
d[0][0] = 'a'

In [58]:
e

[[1, 2, 3], [4, 5, 6]]

In [63]:
c = [1,2,3,4,5,6,7,8]
c = c.reshape((4,2))

AttributeError: 'list' object has no attribute 'reshape'

In [95]:
d = [[1090,2],[3,0],[5,6],[7,8]]
f = np.asarray(d, dtype=np.float)

In [96]:
f

array([[1090.,    2.],
       [   3.,    0.],
       [   5.,    6.],
       [   7.,    8.]])

In [97]:
f[0,0] = 10000000

In [98]:
d

[[1090, 2], [3, 0], [5, 6], [7, 8]]

In [104]:
import numpy as np

d = [[1090,2],[3,0],[5,6],[7,8]]
f = np.asarray(d)
f[0,0] = 0

In [105]:
f

array([[0, 2],
       [3, 0],
       [5, 6],
       [7, 8]])

In [106]:
d

[[1090, 2], [3, 0], [5, 6], [7, 8]]

In [102]:
x = np.ones_like(d)

In [103]:
x

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])