In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,])

In [6]:
b = np.save('sun',a)

In [7]:
%ls

 C 드라이브의 볼륨: SSD
 볼륨 일련 번호: CAB7-4424

 C:\Users\hogoo\Dropbox\python\jupyter\인공지능 기본과정\day13 디렉터리

2019-03-20  오후 04:47    <DIR>          .
2019-03-20  오후 04:47    <DIR>          ..
2019-03-20  오후 04:46    <DIR>          .ipynb_checkpoints
2019-03-20  오후 04:12                27 hello.txt
2019-03-20  오후 04:12                 0 hello2.txt
2019-03-20  오후 04:21                 0 moon.txt
2019-03-20  오후 04:42            34,710 open, with.ipynb
2019-03-20  오후 04:46               140 sun.np.npy
2019-03-20  오후 04:47               140 sun.npy
2019-03-20  오후 03:43             9,936 Untitled.ipynb
2019-03-20  오후 04:46                72 Untitled1.ipynb
               8개 파일              45,025 바이트
               3개 디렉터리  14,591,713,280 바이트 남음


In [9]:
c = np.load('sun.npy')

In [10]:
c

array([1, 2, 3])

In [11]:
a = np.arange(30).reshape(10,3)

In [12]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [16]:
np.mean(a,axis=0)

array([13.5, 14.5, 15.5])

In [17]:
np.mean(a,axis=1)

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28.])

In [15]:
np.mean(a)

14.5

In [19]:
a.sum(axis=0)

array([135, 145, 155])

In [20]:
Docstring:
a.sum(axis=None, dtype=None, out=None, keepdims=False)

Return the sum of the array elements over the given axis.

SyntaxError: invalid syntax (<ipython-input-20-8abc391c8abc>, line 1)

In [22]:
a.dtype

dtype('int32')

In [23]:
a.shape

(10, 3)

In [25]:
a.itemsize

4

In [26]:
a.strides

(12, 4)