In [1]:
import numpy as np

In [4]:
a = [[1.,0.,0.],[0.,1.,2.]]

In [7]:
a

[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]

In [5]:
b = np.array(a)

In [6]:
b

array([[1., 0., 0.],
       [0., 1., 2.]])

In [12]:
b.shape

(2, 3)

In [17]:
b.dtype

dtype('float64')

In [13]:
b.size

6

In [14]:
b.itemsize

8

In [18]:
b.ndim

2

In [23]:
b.strides

(24, 8)

In [26]:
b.argmax() #1차원 배열로 취급했을 때 마지막인자 index

5

In [28]:
c = np.array([1,2,3],dtype=np.float16) #C 기반이기 때문에 데이터타입을 지정할 수 있다.

In [29]:
c.dtype

dtype('float16')

In [31]:
d = np.array([1,2,3], dtype=np.int8)

In [32]:
d.dtype

dtype('int8')

In [33]:
a = b'abc'

In [34]:
c = np.array(a)

In [35]:
c

array(b'abc', dtype='|S3')

In [37]:
c.dtype

dtype('S3')

In [43]:
c #c만 치면 whos의 네임스페이스에서 있는지 없는지 체크

array(b'abc', dtype='|S3')

In [38]:
print(c) #print(c) 치면 __str__()과 같음

b'abc'


In [39]:
whos

Variable   Type       Data/Info
-------------------------------
a          bytes      b'abc'
autopep8   module     <module 'autopep8' from '<...>e-packages\\autopep8.py'>
b          ndarray    2x3: 6 elems, type `float64`, 48 bytes
c          ndarray    : 1 elems, type `|S3`, 3 bytes
d          ndarray    3: 3 elems, type `int8`, 3 bytes
json       module     <module 'json' from 'c:\\<...>\lib\\json\\__init__.py'>
np         module     <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>


In [41]:
c.__repr__()

"array(b'abc', dtype='|S3')"

In [42]:
c.__str__()

"b'abc'"

In [48]:
c = np.array([ [1,2], [3,4] ], dtype=complex) #complex는 복소수 형태

In [49]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [50]:
a=np.array([1,2,3])

In [51]:
a

array([1, 2, 3])

In [60]:
b=a#스왈로카피

In [61]:
b[1]=4

In [62]:
b

array([1, 4, 3])

In [63]:
a

array([1, 4, 3])

In [64]:
c = a.copy()#딥카피

In [66]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [67]:
a+1

array([2, 3, 4])

In [69]:
np.full([2,2],4)

array([[4, 4],
       [4, 4]])

In [76]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])

In [71]:
a+b #elementwise 방식

array([[3, 1],
       [3, 5]])

In [72]:
a@b #matrix 방식


array([[5, 4],
       [3, 4]])

In [73]:
a.dot(b) #벡터 내적

array([[5, 4],
       [3, 4]])

In [74]:
b+=a

In [75]:
b

array([[3, 1],
       [3, 5]])

In [77]:
%timeit sum(range(10000))

194 µs ± 13.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [80]:
%timeit np.sum(np.arange(10000))

15.1 µs ± 506 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [81]:
sum(range(1001))/len(range(1001))

500.0

In [83]:
np.mean(np.arange(1001))

500.0

In [84]:
b = np.arange(3)

In [85]:
b

array([0, 1, 2])

In [88]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [94]:
a = np.arange(1,11).reshape(2,-1)

In [95]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [99]:
a[(a==9) | (a==3)]=0

In [100]:
a

array([[ 1,  2,  0,  4,  5],
       [ 6,  7,  8,  0, 10]])

In [101]:
a[a==4]

array([4])

In [102]:
def f(x,y):
    return 10*x+y

In [103]:
b = np.fromfunction(f,(5,4),dtype=int)

In [105]:
b #함수형 패러다임으로 구현

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [124]:
list(map(lambda x:10**x,a))

[array([1000, 1000, 1000, 1000, 1000], dtype=int32),
 array([    100000,    1000000,   10000000,  100000000, 1000000000],
       dtype=int32)]

In [125]:
a = np.arange(10).reshape(2,5)

In [126]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [127]:
a.flatten()[0]=3

In [129]:
a # flatten은 view. 안바뀐다.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [130]:
a.ravel()[0]=3

In [131]:
a #ravel은 copy.바뀐다.

array([[3, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [134]:
a = np.arange(10).reshape(2,5)
b = np.arange(10,20).reshape(2,5)

In [135]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [136]:
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [141]:
a.dot(b.T)

array([[130, 180],
       [430, 605]])

In [142]:
np.dot(a,b.T)

array([[130, 180],
       [430, 605]])

In [144]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [146]:
np.r_[a,b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [147]:
x = np.r_[a,b]

In [151]:
np.vsplit(x,[0,5])

[array([], shape=(0, 5), dtype=int32), array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]), array([], shape=(0, 5), dtype=int32)]

In [152]:
a = np.array([[2,3],[1,2]])

In [153]:
np.invert(a)

array([[-3, -4],
       [-2, -3]], dtype=int32)

In [154]:
b = np.mat(a)

In [155]:
b

matrix([[2, 3],
        [1, 2]])

In [158]:
b.I

matrix([[ 2., -3.],
        [-1.,  2.]])

In [159]:
b.I@np.array([[1,2],[3,4]])

matrix([[-7., -8.],
        [ 5.,  6.]])